language: php

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

branches:
  only:
    - master
    - /^\d+\.(\d+|x)$/

env:
  # to be removed when tests succeed with Symfony 5.0 (see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2072)
  - SYMFONY_REQUIRE="4.4.*"

matrix:
  fast_finish: true
  include:
    # lowest dependencies
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
    - php: 7.3
    # Symfony 4.4
    - php: 7.4
      env: SYMFONY_REQUIRE="4.4.*"
    # development dependencies
    - php: 7.4
      env: DEPENDENCIES='dev'
  allow_failures:
    - php: 7.4
      env: DEPENDENCIES='dev'

before_install:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini || true
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master
  - if [ "$DEPENDENCIES" != "" ]; then composer config minimum-stability $DEPENDENCIES; fi
  - if [ "$SYMFONY_LTS" != "" ]; then composer require --dev --no-update symfony/lts=$SYMFONY_LTS; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist
  - ./phpunit install

script: ./phpunit
